title: "Raw Thots"
email: "anonymousvista6@gmail.com"
description: >-
  A personal archive of thoughts, emotions, and musings
  written over a few years.

theme: jekyll-theme-minimal

baseurl: ""
url: "https://ayounsome.github.io"

future: true


